In [2]:
import torch

In [2]:
a=torch.ones(1,1,2,2)
kernel = torch.ones(1,1,2,2, requires_grad=True)
c = torch.nn.functional.conv2d(a, kernel, padding=1, stride=1)
out = c.mean()
out.backward()

In [4]:
print(out)
print(kernel.grad)

tensor(1.7778, grad_fn=<MeanBackward0>)
tensor([[[[0.4444, 0.4444],
          [0.4444, 0.4444]]]])


In [3]:
a = torch.tensor([1,2,3,4], dtype=torch.float).view(1,1,1,4)
a1 = torch.tensor([1,2], dtype=torch.float).view(1,1,1,2)
kernel = torch.ones(1,1,1,2, requires_grad=True)
c = torch.nn.functional.conv1d(a, kernel, stride=1)
b = torch.nn.functional.conv1d(a1, kernel, stride=1)
out = (c+b).mean()
out.backward()

In [4]:
print(c, b)
print(out)
print(kernel.grad)

tensor([[[[3., 5., 7.]]]], grad_fn=<MkldnnConvolutionBackward>) tensor([[[[3.]]]], grad_fn=<MkldnnConvolutionBackward>)
tensor(8., grad_fn=<MeanBackward0>)
tensor([[[[3., 5.]]]])
