In [29]:
import torch
from torch.nn import Conv2d
from torch.nn import MSELoss
from torch.optim import SGD, Adam
torch.manual_seed(0)
input = torch.tensor([
    [0,0,5],
    [0,5,5],
    [5,5,10]
], dtype=torch.float).unsqueeze(0).unsqueeze(0)
w = Conv2d(1, 1, kernel_size=2, stride=1)
target = torch.tensor([
    [1, 0],
    [0, 1]
], dtype=torch.float).unsqueeze(0).unsqueeze(0)
print(target.shape)
epoch = 50
# optimizer = SGD(w.parameters(), lr=1e-6)
optimizer = Adam(w.parameters(), lr=1e-2)
for i in range(epoch):
    output = w(input)
    func=MSELoss()
    loss=func(output, target)
    print(loss)
    loss.backward()
    optimizer.step()
    print(w.weight)

torch.Size([1, 1, 2, 2])
tensor(13.9382, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0063,  0.2782],
          [-0.4015, -0.3580]]]], requires_grad=True)
tensor(12.7090, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0159,  0.2879],
          [-0.3918, -0.3483]]]], requires_grad=True)
tensor(11.5777, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0256,  0.2975],
          [-0.3822, -0.3387]]]], requires_grad=True)
tensor(10.5098, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0352,  0.3072],
          [-0.3726, -0.3290]]]], requires_grad=True)
tensor(9.4948, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0449,  0.3169],
          [-0.3628, -0.3193]]]], requires_grad=True)
tensor(8.5295, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0548,  0.3268],
          [-0.3530, -0.3095]]]], requires_grad=True)
tensor(7.6133, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[[[ 0.0647,  0.33